# Use continuumio/miniconda3 as a base image 

# Set /Day6 as a working directory

# Copy environment.yml


# create an environment using environment.yml

# install fastapi[standard] for fastapi's cli on the environment

# expose port 8000


# run the ex01.py as fastapi server.