
# Creating crontab to call the api server
# install cron

# create a log file

#  Add crontab file 
# Note : /etc/cron.d is a directory for cron

# RUN chmod 0644 /etc/cron.d/api-cron
# Apply cron job

# Normally crontab is working on the background.
# However, for the Docker image, this is a single process
# running in the foreground in the container, and remain active.
